#!/usr/bin/perl

use Socket;


socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
setsockopt(SERVEUR, SOL_SOCKET, SO_RUSEADDR, 1);

$addr = sockaddr_in("7777", INADDR_ANY) || die("sockaddr_in");
bind(SERVEUR, $addr) || die("bind error");
listen(SERVEUR, SOMAXCONN) || die("listen error");

while(accept(CLIENT, SERVEUR)){
	autoflush CLIENT 1;
	printf CLIENT while(<CLIENT>);
	close CLIENT;
}

close SERVEUR;
