#!/usr/bin/perl

use Socket;


socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));

$adresse = inet_aton("localhost") || die ("inet_aton");
$adresse_complete = sockaddr_in("7777", $adresse) || die ("sockaddr_in");

connect(SERVEUR, $adresse_complete) || die ("connect");
autoflush SERVEUR 1;

while(1){
	$msg = <STDIN>;
	print SERVEUR $msg;
	
	$msg = <SERVEUR>;
	print $msg;
}

close (SERVEUR);
