#!/usr/bin/perl

use Socket;


socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));

$addr = inet_aton($ARGV[0]) || die ("inet_aton");
$addr = sockaddr_in("80", $addr) || die ("sockaddr_in");

connect(SERVEUR, $addr) || die ("connect");
autoflush SERVEUR 1;
printf SERVEUR "GET /$ARGV[1] HTTP/1.1\nHost: $ARGV[0]\n\n";

print while(<SERVEUR>);

close SERVEUR;
