#!/usr/bin/perl

for (1..$ARGV[0]){
	$pid = fork;
	exec("./rien") if($pid == 0);
	push(@fils, $pid) if($pid > 0); # N'ajoute pas les forks échoués
}

for (@fils){
	waitpid $_, "";
	print "fils $_ mort\n";
}
