#!/usr/bin/perl

$file = $ARGV[0];

open(CONFIG, "<$file") || die("Impossible de charger le fichier");
@content = <CONFIG>;
close(CONFIG);

#print @content;

for (@content) {

    if (/^set/) {
	@set[$i++] = $_;
    }
}

for (@set) {
    
    if (/set\s+port\s+(\d+)/) {
	$port = $1;
    } elsif (/set\s+default\s+(.+)/) {
	$default = $1;
    } elsif (/set\s+index\s+(.+)/) {
	$index = $1;
    } elsif (/set\s+clients\s+(.+)/) {
	$clients = $1;
    } elsif (/set\s+logfile\s+(.+)/) {
	$logfile = $1;
    } elsif (/set\s+basedir\s+(.+)/) {
	$basedir = $1;
    }

}

print $port."\n";
print $default."\n";
print $index."\n";
print $clients."\n";
print $logfile."\n";
print $basedir."\n";
