#!/usr/bin/perl

#use Data::Dumper;

$file = $ARGV[0];

open(CONFIG, "$file") || die("Impossible de charger le fichier");

while(<CONFIG>) {
    if(/^set\s+(.+)\s+(.+)/){
	${$1} = $2;
    } elsif (/^route\s+(.+?)\s+to\s+(.+)/) {
	$route{$1} = $2;
    } elsif (/^exec\s+(.+?)\s+from\s+(.+)/) {
	$exe{$1} = $2;
    } 
}

close(CONFIG);

print $port."\n";
print $default."\n";
print $index."\n";
print $clients."\n";
print $logfile."\n";
print $basedir."\n";
#print Dumper(\%route)."\n";
@tabRoute = %route;
@tabExec = %exe;

$" = " => ";

#for (@tabRoute) {
#    print $_."\n";
#}
print "@tabRoute\n";
print "@tabExec\n";


